openapi: 3.0.0
info:
  title: Minha API REST
  version: 0.1
servers:
  - url: http://localhost:3000/
tags:
  - name: usuarios
paths:
  /usuarios:
    post:
      tags:
        - usuarios
      summary: Cadastrar novo usuário
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Usuario'
      responses:
        '201':
          description: Criado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Usuario'
        '422':
          description: Erro de Validação
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                    example: Email e Senha são obrigatórios
  
  /usuarios/{id}:
    delete:
      tags:
        - usuarios
      summary: Remover usuário
      security:
        - JWTAuth: []
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: ID do usuário
      responses:
        '204':
          description: No Content (Removido com sucesso)

  /usuarios/login:
    post:
      tags:
        - usuarios
      summary: Realizar Login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - usuario
                - senha
              properties:
                usuario:
                  type: string
                  example: usuario@email.com
                senha:
                  type: string
                  example: 123456
      responses:
        '200':
          description: Sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        '401':
          description: Credenciais inválidas
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Mensagem'

  /usuarios/renovar:
    post:
      tags:
        - usuarios
      summary: Renovar Token JWT
      security:
        - JWTAuth: []
      responses:
        '200':
          description: Token Renovado
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        '401':
          description: Token Inválido
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Mensagem'

components:
  schemas:
    Usuario:
      type: object
      required:
        - email
        - senha
      properties:
        email:
          type: string
          example: teste@teste.com
        senha:
          type: string
          example: 123456
    
    Mensagem:
      type: object
      properties:
        msg:
          type: string

  securitySchemes:
    JWTAuth:
      type: apiKey
      in: header
      name: authorization